//
// Created by kuzne on 11/20/2017.
//

#ifndef ASSEMBLER_COMMANDS_H
#define ASSEMBLER_COMMANDS_H

DEF_CMD(5, PUSH_R_N, 2)
DEF_CMD(6, POP_R_N, 2)
DEF_CMD(7, PUSH, 2)
DEF_CMD(8, POP, 1)
DEF_CMD(9, ADD, 1)
DEF_CMD(10, MULTIPLY, 1)
DEF_CMD(11, SUB, 1)
DEF_CMD(12, DIV, 1)

#endif //ASSEMBLER_COMMANDS_H
